export enum USER_ACTION_TYPE{
    SET_CURRENT_USER="user/SET_CURRENT_USER",
    CHECK_USER_SESSION='user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START='user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START='user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS='user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED='user/SIGN_IN_FAILED',
    SIGN_UP_STARTED='user/SIGN_UP_STARTED',
    SIGN_UP_SUCCESS='user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILED='user/SIGN_UP_FAILED',
    SIGNOUT_STARTED="user/SIGNOUT_STARTED",
    SIGNOUT_SUCCSESS="user/SIGNOUT_SUCCSESS",
    SIGNOUT_FAILED="user/SIGNOUT_FAILED"
}